### ISSUE TITLE
Bug: Mining anywhere other than mines.

### ISSUE THREAD

**Issue by ShepMC** [MCPrison/Server#117]
You can reportedly get gembooks from mining in spawn or anywhere other than the mine. aswell as in the mine ofc.

**Comment by HijackingMC** [comment]
@ShepMC 

The reason why the user got a gembook was because of their prospector enchantment. When they do something, whether the event is actually cancelled or not them mining a block in spawn said to the server Hey, I'm no longer AFK and the user had waited the time between book finds.

If you can double check this with the user who reported it, I'd appreciate it :P.
