### ISSUE TITLE
ToDo: Bugs/Sugestions

### ISSUE THREAD

**Issue by Serayne92z** [MCPrison/Server#119]
This needs to be fixed. https://youtu.be/m_w2CuSAGAY Player suggested "I came up with the solution to buff how large the jackhammer was in size but nerf the proc rate"

Auto sell should be % of inventory/backpacks based. (Max level 100%)

Multiple players have told me the sell multi enchant on the backpacks doesn't seem to be functioning as well at higher levels.

**Comment by ShepMC** [comment]
I’ll send this here to give more of an insight: I have been speaking to spoon & jake and some others and came to the conclusion that JH is quite op at the end let alone it procs a lot so it makes the player lag quite a lot. Because of this me and spoon thought of having it so JH starts off at level 1 as a 20x20 square being mined and as you increase the levels it slowly procs more and the size gets bigger until at the end it mines the whole mine layer and procs a decent amount but doesnt proc constantly so like reduce the amount it procs quite a lot really but make the size get bigger so its still more rewarding but shouldnt be op if done right.

**Comment by HijackingMC** [comment]
What do you recommend as the solution @ShepMC?

**Comment by ShepMC** [comment]
so like at level 1 it’s 20x20 and low proc rate then eventually goes up to like at max being 50% proc rate and mining the whole mine. Just finalising details

**Comment by HijackingMC** [comment]
That's not what the video is showing....

So,
 The pickaxe has explosive, laser, and jackhammer I believe..

That means,
 x% chance to proc any of those.

If I break x block I have the chance to proc, jackhammer, laser or explosive. Your math just doesn't make sense taking into consideration all of the enchantments.

**Comment by ShepMC** [comment]
That video was first made because it is laggy as fuck and I spoke with spoon and the way that we came up with was that.
